version: '3.8'

services:
  web:
    build: .
    container_name: shopware-reports-app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped

volumes:
  redis_data: